### ISSUE TITLE
Support for eslint 7

### ISSUE THREAD

**Issue by felicemcc** [team-rawbot/eslint-config-rawbot#8]
When using Django Template out of the box we get this warning:

npm WARN eslint-config-rawbot@1.1.1 requires a peer of eslint@>= 5 < 7 but none is installed. You must install peer dependencies yourself.

Eslint is at 7.22.0 as of today, in one project I just had to downgrade to version 6.8

**Comment by LeBenLeBen** [comment]
@felicemcc I think you can use it with Eslint 7, I mean if you run EsLint and doesn’t get errors of unknown rules or similar, it’s ok. It’s just a warning because we fixed the peer dependency.

But thanks for the heads up, we indeed need to fix that.
